env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
  sourceType: 'module'
  ecmaFeatures: impliedStrict
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars:
    - error
    - vars: local
      args: none
  no-console: off
  require-atomic-updates: off
  no-async-promise-executor: off
  no-redeclare: off
