env:
  es6: true
  node: true
parserOptions:
  ecmaVersion: 8
  ecmaFeatures: impliedStrict
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars:
    - error
    - vars: local
      args: none
  no-console: off
